mysql:
  image: mysql
  container_name: database
  ports:
    - 3306:3306
  environment:
    MYSQL_DATABASE: laravel
    MYSQL_ROOT_PASSWORD: 123456

php:
  image: php:fpm-alpine
  container_name: php
  ports:
    - 8082:80
  volumes:
    - .:/var/www/laravel
  entrypoint:
    - php-fpm

